<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="junit.tutorial.CalculatorTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2018-08-15T15:00:31" hostname="onesword0618-ThinkPad-X230" time="0.006">
  <properties/>
  <testcase name="multiplyで5と7の乗算結果が取得できる" classname="junit.tutorial.CalculatorTest" time="0.004"/>
  <testcase name="multiplyで3と4の乗算結果が取得できる" classname="junit.tutorial.CalculatorTest" time="0.001"/>
  <testcase name="divideで３と２の除算結果が取得できる" classname="junit.tutorial.CalculatorTest" time="0.0"/>
  <testcase name="divideで５と０のときにIllegalArgumentExceptionを送出する" classname="junit.tutorial.CalculatorTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
